In [156]:
import numpy as np # import: 라이브러리 불러오기, numpy 불러오는데, 이를 np로 지금부터 부르겠단 것

my_array = np.arange(10000)
my_list = list(range(10000))
my_array

array([   0,    1,    2, ..., 9997, 9998, 9999], shape=(10000,))

In [2]:
my_list2 = [i * 2 for i in my_list]
my_array2 = my_array * 2 # np는 배열 편하게 다루기 위해 사용 >> numpy에 *2하면, 각 요소 하나하나에 접근해 *2해줌
    # numpy는 배열 형태 데이터 다루는 데 특화 >> 시간 단축해 효율적으로 다룰 수 있음

In [3]:
# 2차원 리스트: 리스트 내에 리스트 넣은 것
a = [
    [1, 1.2, 3],
    [-123, 123, 0]
]
# 일괄적으로 데이터 유형 정수에서 소수로 동일히 만들어줌 >> 연산 편하게 하기 위해 더 연산 편한 쪽으로 데이터 형태 바꾼 것
    

data = np.array(a)
print(data)

[[   1.     1.2    3. ]
 [-123.   123.     0. ]]


In [5]:
# 0차원: 스칼라 >> 단일 데이터, 1차원: 벡터, 2차원: 행렬(matrix), 3차원: 텐서(tenser)
print(data * 10) # 곱셈 연산할 때, 각 하나의 모든 데이터에 해당 곱셈 연산 수행 >> 파이썬 기본 문법일 시 list를 10번 반복하는 식

print(data + data) # 리스트끼리 덧셈도 가능 >> 각 요소끼리 더해줌

print(data.shape) # 가로-세로 크기 알려줌 >> 데이터 프레임 모양 알려주는 것
print(data.dtype) # 세부 데이터 알려줌 >> 소수일 시 flort로 알려주는 것

[[   10.    12.    30.]
 [-1230.  1230.     0.]]
[[   2.     2.4    6. ]
 [-246.   246.     0. ]]
(2, 3)
float64


In [9]:
# ndarry 생성하기


data1 = [1,2,3,4,5]
arr1 = np.array(data1) # 어레이 형태로 변환해서 arr1 변수에 넣기
arr1
print(type(arr1)) # <class 'numpy.ndarray'>: numpy 안에 있는 ndarray라는 클래스 >> 넘파이에서 만들어지는 모든 어레이는 ndarray에서 만들어짐


<class 'numpy.ndarray'>


In [12]:
arr2 = np.array([[1.1, 1.2],[3.3, 4.4]]) # 2차원 배열 만들기: 리스트 만든 뒤, 이를 np.array에 넣기
print(arr2)
print(type(arr2))

[[1.1 1.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [16]:
# 배열의 차원 수를 알려줌
print(arr1.ndim) # 1차원 데이터 == 벡터
print(arr2.ndim) # 2차원 데이터 == 

# 모든 데이터의 구조 보기
print(arr1.shape) # 0차원의 데이터 값만 있는 구조라서 y값 비어 있는 것
print(arr2.shape)

1
2
(5,)
(2, 2)


In [21]:
print(np.zeros(10)) # 0이 10개 있는 배열 만들어줌 >> 0이라는 리스트를 10번 반복해달라는 것과 동일한 원리
    # 배열 구조를 먼저 잡고 이후 데이터 값 할당하기 위해 사용

print(np.zeros(10))
print(np.zeros( (5, 5) )) # 튜플 (5,5) 입력하는데, 이는 가로-세로 5개씩인데, 값은 0으로 채워진 배열 만들기
print(np.empty((2,2,2))) # 가로세로 2,2인 2개의 서로 다른 배열 만드는 것

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [23]:
print(np.arange(10)) # 0-9까지의 순서 있는 배열 만들어줌

[0 1 2 3 4 5 6 7 8 9]


In [28]:
## ndarray 자료형

#배열 생성할 때 자료형 변경하기
    # dtype 인자 직접 설정해서 해당 배열을 어떻게 바라볼 것인지 지정 가능
arr1 = np.array([1,2,3], dtype= np.float64)
arr2 = np.array([1,2,3], dtype= np.int32)

print(arr1.dtype) # int 형태의 64비트 형태라고 출력
print(arr2.dtype)

float64
int32


In [34]:
# 배열 먼저 만든 이후, 자료형 변경하기
arr1 = np.array([1,2,3])
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64) # 형변환해주는 함수
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [37]:
# 소수를 정수로 변경한다면, 반올림 아니라 소수점 이후는 버림처리해서 정수형으로 강제로 형변환됨
arr2 = np.array([1.1,2.2,3.3])
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64)
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3]
int64


In [46]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

# 동일 위치끼리 연산 이뤄짐
print(arr * arr)
print(arr + arr)
print(1 / arr)
print(arr ** 3)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [50]:
arr2 = np.array([[3,2,1], [1,2,3]])
print(arr)
print(arr2)

print(arr > arr2) # 두 배열 중 무엇이 큰지 비교하기 >> 전체 행렬이 아닌, 각 위치에 따른 데이터끼리 비교

print(arr == arr2) 

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[False  True False]
 [False False False]]


In [55]:
arr = np.arange(10) # 0-9까지 값 넣은 배열 만듦
print(arr)
arr[5] # 5번째 데이터 값 접근
print(arr[2:5]) # 2번째부터 4번째까지 데이터 슬라이싱해 출력

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [56]:
# 배열 슬라이싱 한 뒤 대신 10 넣기
arr[2:5] = 10
print(arr) # 기존 2, 3, 4 대신 10, 10, 10 넣음
# 파이썬에서 슬라이싱: 원본 카피한 버전을 슬라이싱해서 원본은 수정X >> 근데 넘파이는 원본도 바뀌게 설계됨
    # 넘파이는 대량 데이터 다루는 모듈임 >> 메모리 절약 위해 원본 수정하도록 함

[ 0  1 10 10 10  5  6  7  8  9]


In [60]:
# 2차원 데이터 색인하기
arr = np.array([[1,2,3],[4,5,6]])
print(arr) # 2행 3열 형태의 배열 만들어짐
# 5 접근해 출력
print(arr[1,1]) # 1번째 행의, 1번째 열에 접근한단 것

[[1 2 3]
 [4 5 6]]
5


In [110]:
# 3차원 데이터 색인
arr3d = np.array([[[1,2,3], [4,5,6], [7,8,9]],
                [[11,12,13], [14,15,16], [17,18,19]],
                [[11, 22, 33], [44,55,66], [77,88,99]]])

# 22 찾기
print(arr3d[2, 0, 1]) # 2번째 행의, 0번째 열의, 1번재 데이터 출력

22


In [111]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[11, 22, 33],
        [44, 55, 66],
        [77, 88, 99]]])

In [135]:
arr3d[:1] # 0번째부터 1번재 열까지만 자르기

# 0: index 접근을 하는 것 >> 0번째 행에 들어간 뒤
print(arr3d)
print(arr3d[0, 1:][1:]) # 0: 0번째 행 선택, 1: : 0번째 행의 1번째 행부터 끝까지 선택, 1: : 그 1번째 행의 1번째 행부터 끝까지
print(arr3d[0, 1:, 1:]) # 0번째 행 선택, 1: : 0번째 행의 1번째 행부터 선택, 1: 그 1번째 행의 1번째 열부터 끝까지 선택

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]]
[[7 8 9]]
[[5 6]
 [8 9]]


In [74]:
# 이름 4개 들어 있는 list
names = np.array(['hong', 'kim', 'hong', 'kim'])
# data 중 hong의 데이터만 고르기
data = np.array([['math', 60], ['math', 90], ['engilsh', 70], ['engilsh', 50]])

# 그러기 위해 먼저 불리언 데이터로 만들어야 함
    # 넘파이에서는 ==으로 비교 가능
names == 'hong'

array([ True, False,  True, False])

In [75]:
# 데이터로 인덱스 접근할 때 names == 'hong'을 활용할 것
data[names == 'hong'] # data 안에 [[true], [fals], [true], [fals]]를 넣어서, true 값만 출력하는 원리
# 특정 조건에 맞는 데이터 고를 때 활용

array([['math', '60'],
       ['engilsh', '70']], dtype='<U21')

In [79]:
data[names == 'hong', 1] # hong의 수학, 영어 점수만 출력하기 >> 인덱스 접근한 것
data[names == 'hong', :1] # 0번째 출력 >> 슬라이싱 한 것
# 인덱스 / 슬라이싱 접근 따라 출력된 데이터 형태 다름

array([['math'],
       ['engilsh']], dtype='<U21')

In [82]:
# hong이 아닌 사람을 고르기
print(names != 'hong') # !=: hong이 아닌 이름을 고르기
print(~(names == 'hong')) # ~: 계산 결과 출력한 뒤, 그 결과의 역을 출력하는 것

[False  True False  True]
[False  True False  True]


In [83]:
# 결과 연산한 값을 변수와 같은 컨디션에 저장 >> 그런 뒤 컨디션을 통해 인덱스 접근하는 게 일반적
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['engilsh', '50']], dtype='<U21')

In [85]:
arr = np.zeros((8, 4))
print(arr) # 8줄의 4칸짜리 배열 형성

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [87]:
# 같은 줄의 데이터는 동일 숫자 값 같도록 구조 잡기
for i in range(8):
    arr[i] = i
print(arr)



[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [89]:
# 팬시 색인: 2, 4, 6번째 열만 색인 가능
# 대괄호 안에 대괄호 >> 이후 입력하면, 원하는 것만 출력 가능, 내가 지정한 순서대로 출력 가능 
arr[[4, 3, 0, 5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [91]:
# 음수 인덱스 접근도 가능
arr[[-3, -5, -1]] # 뒤에서 3번째, 5번째, 1번째 행 선택

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [101]:
# 행과 열 동시에 선택하기

arr = np.arange(32).reshape(8,4) # 0~31까지의 배열 만들기
    # 한줄의 32개 있는 것을, 8,4 형태로 다시 구조화하기
print(arr)
print(arr[[1, 5]]) # 1번째, 5번째 행만 선택
# 특정 2개만 접근하고 싶다면
print(arr[[1, 5], [2, 3]]) # 1번째 행의 2번째 열, 5번째 행의 3번재 열 출력

# 팬시 색인 이후 다시 팩시 색인하기
arr[[1, 5]][:, [2, 3]] # 1번째 행의 2~3번째 열, 5번째 행의 2~3번째 열 선택

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  5  6  7]
 [20 21 22 23]]
[ 6 23]


array([[ 6,  7],
       [22, 23]])

In [140]:
### 배열 전치

arr = np.arange(6).reshape(2,3) # 0~14 숫자를 (3,5) 형태 배열 만들기
print(arr)

print(arr.T) # 배열 반대로, 5열 3행으로 전환 >> 축 변경 시 사용

# 그러면 행렬의 곱셈 가능하단 것

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [142]:
# 기존
arr * 3 # 각 하나의 요소마다 3씩 곱하게 됨

# 행렬의 곱
arr @ arr.T
np.dot(arr, arr.T) # 위 행렬의 곱 코드와 동일 작동

# ai 생태계에서 중요한 것 = 연산을 얼마나 빨리 하느냐, 어떤 연산을 하느냐 >> 이때 주로 행렬의 곱 연산을 함
    # 행렬 얼마나 빨리 처리하는지가 성능 판가름 하는 것임 >> 그에 따라 고성능인지 판단되는 것

# 0*0 + 

array([[ 5, 14],
       [14, 50]])

In [146]:
# 3,3 배열 만들기 >> 정규분포 따르는 랜덤 숫자 넣기
samples = np.random.standard_normal(size = (3,3)) # random 내의 standard_normal 기능 활용하겠단 것
print(samples)

[[-0.76183269 -1.77561372  0.66842651]
 [ 0.29934745  1.12619107 -0.59061693]
 [ 0.93856184  0.30366721  0.55314052]]


In [151]:
# 배열 넘기면 모든 데이터를 루트 씌워 계산하기
arr1 = np.sqrt(samples)

# nan: 숫자가 아닙니다라는 것 >> 파이썬의 none과 같은 의미
    # 루트 씌웠는데 그 수가 음수일 때 계산 못하니, 숫자 없다는 빈칸으로 출력한 것
    # nan: 결측치임 >> 결측치: 데이터 없는 경우

C:\Users\1-08\AppData\Local\Temp\ipykernel_8136\3314444035.py:2: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples)


In [149]:
arr2 = np.abs(samples)
print(arr2)
# 절대값으로 바꿔줌

[[0.76183269 1.77561372 0.66842651]
 [0.29934745 1.12619107 0.59061693]
 [0.93856184 0.30366721 0.55314052]]


In [152]:
np.isnan(arr1) # 현재 내 배열 중 nan이 있는지 확인해줌 >> true면 nan 값 있단 것

array([[ True,  True, False],
       [False, False,  True],
       [False, False, False]])